//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notes.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ActionSheetOption_Cancel {
            get {
                return ResourceManager.GetString("ActionSheetOption_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        public static string ActionSheetOption_LocalBackup_CreateBackup {
            get {
                return ResourceManager.GetString("ActionSheetOption_LocalBackup_CreateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Permanently.
        /// </summary>
        public static string ActionSheetOption_LocalBackup_DeletePermanently {
            get {
                return ResourceManager.GetString("ActionSheetOption_LocalBackup_DeletePermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string ActionSheetOption_OrderBy_DateCreated {
            get {
                return ResourceManager.GetString("ActionSheetOption_OrderBy_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        public static string ActionSheetOption_OrderBy_DateModified {
            get {
                return ResourceManager.GetString("ActionSheetOption_OrderBy_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ActionSheetOption_OrderBy_Name {
            get {
                return ResourceManager.GetString("ActionSheetOption_OrderBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ActionSheetOption_OrderBy_Size {
            get {
                return ResourceManager.GetString("ActionSheetOption_OrderBy_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Backup File.
        /// </summary>
        public static string ActionSheetTitle_ChooseBackupFile {
            get {
                return ResourceManager.GetString("ActionSheetTitle_ChooseBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup to file format:.
        /// </summary>
        public static string ActionSheetTitle_ChooseBackupFileFormat {
            get {
                return ResourceManager.GetString("ActionSheetTitle_ChooseBackupFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By:.
        /// </summary>
        public static string ActionSheetTitle_OrderBy {
            get {
                return ResourceManager.GetString("ActionSheetTitle_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do what with existing notes, folders and style sheets?.
        /// </summary>
        public static string ActionSheetTitle_QueryBackupExisting {
            get {
                return ResourceManager.GetString("ActionSheetTitle_QueryBackupExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder to quick access?.
        /// </summary>
        public static string Alert_AddFolderToQuickAccess_Message {
            get {
                return ResourceManager.GetString("Alert_AddFolderToQuickAccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickAccess.
        /// </summary>
        public static string Alert_AddFolderToQuickAccess_Title {
            get {
                return ResourceManager.GetString("Alert_AddFolderToQuickAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note to quick access?.
        /// </summary>
        public static string Alert_AddNoteToQuickAccess_Message {
            get {
                return ResourceManager.GetString("Alert_AddNoteToQuickAccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Access.
        /// </summary>
        public static string Alert_AddNoteToQuickAccess_Title {
            get {
                return ResourceManager.GetString("Alert_AddNoteToQuickAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can be found at:.
        /// </summary>
        public static string Alert_BackupComplete_Message {
            get {
                return ResourceManager.GetString("Alert_BackupComplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Complete.
        /// </summary>
        public static string Alert_BackupComplete_Title {
            get {
                return ResourceManager.GetString("Alert_BackupComplete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup was restored successfully..
        /// </summary>
        public static string Alert_BackupRestoreComplete_Message {
            get {
                return ResourceManager.GetString("Alert_BackupRestoreComplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Restored.
        /// </summary>
        public static string Alert_BackupRestoreComplete_Title {
            get {
                return ResourceManager.GetString("Alert_BackupRestoreComplete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered loading chosen backup file.
        /// </summary>
        public static string Alert_BackupRestoreFailed_Message {
            get {
                return ResourceManager.GetString("Alert_BackupRestoreFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load Backup.
        /// </summary>
        public static string Alert_BackupRestoreFailed_Title {
            get {
                return ResourceManager.GetString("Alert_BackupRestoreFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No local backups exist.
        /// </summary>
        public static string Alert_BackupsFolderEmpty_Message {
            get {
                return ResourceManager.GetString("Alert_BackupsFolderEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups Folder is Empty.
        /// </summary>
        public static string Alert_BackupsFolderEmpty_Title {
            get {
                return ResourceManager.GetString("Alert_BackupsFolderEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All existing notes, folders, and style sheets will be deleted.
        /// </summary>
        public static string Alert_ConfirmDeleteExisting_Message {
            get {
                return ResourceManager.GetString("Alert_ConfirmDeleteExisting_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait, NO!.
        /// </summary>
        public static string Alert_ConfirmDeleteExisting_OptionCancel {
            get {
                return ResourceManager.GetString("Alert_ConfirmDeleteExisting_OptionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete!.
        /// </summary>
        public static string Alert_ConfirmDeleteExisting_OptionDelete {
            get {
                return ResourceManager.GetString("Alert_ConfirmDeleteExisting_OptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Alert_ConfirmDeleteExisting_Title {
            get {
                return ResourceManager.GetString("Alert_ConfirmDeleteExisting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete folder and all contents?.
        /// </summary>
        public static string Alert_ConfirmDeleteFolder_Message {
            get {
                return ResourceManager.GetString("Alert_ConfirmDeleteFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Folder?.
        /// </summary>
        public static string Alert_ConfirmDeleteFolder_Title {
            get {
                return ResourceManager.GetString("Alert_ConfirmDeleteFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this note?.
        /// </summary>
        public static string Alert_ConfirmDeleteNote_Message {
            get {
                return ResourceManager.GetString("Alert_ConfirmDeleteNote_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Note?.
        /// </summary>
        public static string Alert_ConfirmDeleteNote_Title {
            get {
                return ResourceManager.GetString("Alert_ConfirmDeleteNote_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create backup because permission to write to storage was denied..
        /// </summary>
        public static string Alert_CreateBackupPermissionDenied_Message {
            get {
                return ResourceManager.GetString("Alert_CreateBackupPermissionDenied_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        public static string Alert_CreateBackupPermissionDenied_Title {
            get {
                return ResourceManager.GetString("Alert_CreateBackupPermissionDenied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All text copied to clipboard.
        /// </summary>
        public static string Alert_CSSCopied_Message {
            get {
                return ResourceManager.GetString("Alert_CSSCopied_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied CSS.
        /// </summary>
        public static string Alert_CSSCopied_Title {
            get {
                return ResourceManager.GetString("Alert_CSSCopied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without saving changes?.
        /// </summary>
        public static string Alert_ExitWithoutSaving_Message {
            get {
                return ResourceManager.GetString("Alert_ExitWithoutSaving_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        public static string Alert_ExitWithoutSaving_Title {
            get {
                return ResourceManager.GetString("Alert_ExitWithoutSaving_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; not found in folder &quot;{1}&quot;.
        /// </summary>
        public static string Alert_FolderNotFoundInFolder_Message {
            get {
                return ResourceManager.GetString("Alert_FolderNotFoundInFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All text copied to clipboard.
        /// </summary>
        public static string Alert_HtmlCopied_Message {
            get {
                return ResourceManager.GetString("Alert_HtmlCopied_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied HTML.
        /// </summary>
        public static string Alert_HtmlCopied_Title {
            get {
                return ResourceManager.GetString("Alert_HtmlCopied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All text copied to clipboard.
        /// </summary>
        public static string Alert_MarkdownCopied_Message {
            get {
                return ResourceManager.GetString("Alert_MarkdownCopied_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied Markdown.
        /// </summary>
        public static string Alert_MarkdownCopied_Title {
            get {
                return ResourceManager.GetString("Alert_MarkdownCopied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note &quot;{0}&quot; not found in folder &quot;{1}&quot;.
        /// </summary>
        public static string Alert_NoteNotFoundInFolder_Message {
            get {
                return ResourceManager.GetString("Alert_NoteNotFoundInFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Access Folder &quot;{0}&quot; not found..
        /// </summary>
        public static string Alert_QuickAccessFolderNotFound_Message {
            get {
                return ResourceManager.GetString("Alert_QuickAccessFolderNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Access Note &quot;{0}&quot; not found..
        /// </summary>
        public static string Alert_QuickAccessNoteNotFound_Message {
            get {
                return ResourceManager.GetString("Alert_QuickAccessNoteNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder from quick access?.
        /// </summary>
        public static string Alert_RemoveFolderFromQuickAccess_Message {
            get {
                return ResourceManager.GetString("Alert_RemoveFolderFromQuickAccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Access.
        /// </summary>
        public static string Alert_RemoveFolderFromQuickAccess_Title {
            get {
                return ResourceManager.GetString("Alert_RemoveFolderFromQuickAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove note from quick access?.
        /// </summary>
        public static string Alert_RemoveNoteFromQuickAccess_Message {
            get {
                return ResourceManager.GetString("Alert_RemoveNoteFromQuickAccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickAccess.
        /// </summary>
        public static string Alert_RemoveNoteFromQuickAccess_Title {
            get {
                return ResourceManager.GetString("Alert_RemoveNoteFromQuickAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to restore backup because permission to read from storage was denied..
        /// </summary>
        public static string Alert_RestoreBackupPermissionDenied_Message {
            get {
                return ResourceManager.GetString("Alert_RestoreBackupPermissionDenied_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        public static string Alert_RestoreBackupPermissionDenied_Title {
            get {
                return ResourceManager.GetString("Alert_RestoreBackupPermissionDenied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder does not have a parent folder..
        /// </summary>
        public static string Alert_RootFolderHasNoParent_Message {
            get {
                return ResourceManager.GetString("Alert_RootFolderHasNoParent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Error.
        /// </summary>
        public static string Alert_TemplateError_Title {
            get {
                return ResourceManager.GetString("Alert_TemplateError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AlertOption_Cancel {
            get {
                return ResourceManager.GetString("AlertOption_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AlertOption_No {
            get {
                return ResourceManager.GetString("AlertOption_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertOption_OK {
            get {
                return ResourceManager.GetString("AlertOption_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AlertOption_Yes {
            get {
                return ResourceManager.GetString("AlertOption_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoteSharp.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ColorPicker_Copy_Button {
            get {
                return ResourceManager.GetString("ColorPicker_Copy_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        public static string ColorPicker_Title {
            get {
                return ResourceManager.GetString("ColorPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContextAction_Delete {
            get {
                return ResourceManager.GetString("ContextAction_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string ContextAction_Move {
            get {
                return ResourceManager.GetString("ContextAction_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ContextAction_Rename {
            get {
                return ResourceManager.GetString("ContextAction_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Quick Access.
        /// </summary>
        public static string ContextAction_ToggleQuickAccess {
            get {
                return ResourceManager.GetString("ContextAction_ToggleQuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Markdown Reference and Test
        ///
        ///Markdown is a syntax for describing rich-text components via clean and readable plaintext.
        ///
        ///Paragraphs are separated by an empty line.
        ///
        ///## Headings
        ///
        ///Headings are done with hash chars like this.
        ///
        ///``` 
        ///# First Level Head
        ///
        ///## Second Level Head
        ///
        ///### Third Level Head
        ///
        ///#### Fourth Level Head
        ///
        ///##### Fifth Level Head
        ///
        ///###### Sixth Level Head
        ///``` 
        ///# First Level Head
        ///
        ///## Second Level Head
        ///
        ///### Third Level Head
        ///
        ///#### Fourth Level Head
        ///
        ///##### Fifth Level Hea [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MarkdownReferenceAndTest {
            get {
                return ResourceManager.GetString("MarkdownReferenceAndTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MasterOption_About {
            get {
                return ResourceManager.GetString("MasterOption_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Access.
        /// </summary>
        public static string MasterOption_QuickAccess {
            get {
                return ResourceManager.GetString("MasterOption_QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MasterOption_Settings {
            get {
                return ResourceManager.GetString("MasterOption_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Sheets.
        /// </summary>
        public static string MasterOption_StyleSheets {
            get {
                return ResourceManager.GetString("MasterOption_StyleSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body { 
        ///  background: #1D1D1D; 
        ///  color: #DDDDDD;
        ///  line-height: 1.4;
        ///  font-size: 16;
        ///}
        ///
        ///hr{
        ///  border: 0px;
        ///  border-bottom: 1.2px solid #303030;
        ///}
        ///
        ///blockquote {
        ///  border-left: 4px solid #303030;
        ///  font-style: italic;
        ///  margin-left: 0;
        ///  padding-left: 10;
        ///  color: #BBBBBB
        ///}
        ///
        ////* -- HEAD ------------------------ */
        ///
        ///h1, h2, h3, h4, h5, h6 {
        ///  font-weight: 500;
        ///  margin-top: 24px;
        ///  margin-bottom: 16px;
        ///}
        ///
        ///h1, h2 {
        ///  padding-bottom: .3em;
        ///  border-bottom: 1px solid #303030;
        ///}
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ModernDarkCSS {
            get {
                return ResourceManager.GetString("ModernDarkCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body { 
        ///  background: #F6F5F5; 
        ///  color: #272727;
        ///  line-height: 1.4;
        ///  font-size: 16;
        ///}
        ///
        ///hr{
        ///  border: 0px;
        ///  border-bottom: 1px solid #DDDDDD;
        ///}
        ///
        ///blockquote {
        ///  border-left: 4px solid #DDDDDD;
        ///  font-style: italic;
        ///  margin-left: 0;
        ///  padding-left: 10;
        ///  color: #666666;
        ///}
        ///
        ////* -- HEAD ------------------------ */
        ///
        ///h1, h2, h3, h4, h5, h6 {
        ///  font-weight: 500;
        ///  margin-top: 24px;
        ///  margin-bottom: 16px;
        ///}
        ///
        ///h1, h2 {
        ///  padding-bottom: .3em;
        ///  border-bottom: 1px solid #DDDDDD;
        ///}
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ModernLightCSS {
            get {
                return ResourceManager.GetString("ModernLightCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Name....
        /// </summary>
        public static string NoteEntryPage_NamePlaceholder {
            get {
                return ResourceManager.GetString("NoteEntryPage_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Note Text....
        /// </summary>
        public static string NoteEntryPage_TextPlaceholder {
            get {
                return ResourceManager.GetString("NoteEntryPage_TextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string PageTitle_About {
            get {
                return ResourceManager.GetString("PageTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Preview.
        /// </summary>
        public static string PageTitle_HtmlPreview {
            get {
                return ResourceManager.GetString("PageTitle_HtmlPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Preview.
        /// </summary>
        public static string PageTitle_MarkdownPreview {
            get {
                return ResourceManager.GetString("PageTitle_MarkdownPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown View.
        /// </summary>
        public static string PageTitle_MarkdownView {
            get {
                return ResourceManager.GetString("PageTitle_MarkdownView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To:.
        /// </summary>
        public static string PageTitle_Move {
            get {
                return ResourceManager.GetString("PageTitle_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Access.
        /// </summary>
        public static string PageTitle_QuickAccess {
            get {
                return ResourceManager.GetString("PageTitle_QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string PageTitle_RootFolder {
            get {
                return ResourceManager.GetString("PageTitle_RootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading Style Sheets.
        /// </summary>
        public static string PageTitle_StyleSheets {
            get {
                return ResourceManager.GetString("PageTitle_StyleSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose CSS.
        /// </summary>
        public static string PageTitle_StyleSheetSelection {
            get {
                return ResourceManager.GetString("PageTitle_StyleSheetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder of the same name already exists in the folder; please input a different name.
        /// </summary>
        public static string Prompt_FolderNameConflict_Message {
            get {
                return ResourceManager.GetString("Prompt_FolderNameConflict_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name Conflict.
        /// </summary>
        public static string Prompt_FolderNameConflict_Title {
            get {
                return ResourceManager.GetString("Prompt_FolderNameConflict_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input name for folder.
        /// </summary>
        public static string Prompt_GetFolderName_DefaultMessage {
            get {
                return ResourceManager.GetString("Prompt_GetFolderName_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input name for note.
        /// </summary>
        public static string Prompt_GetNoteName_DefaultMessage {
            get {
                return ResourceManager.GetString("Prompt_GetNoteName_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name, please input a name that does not contain any of the characters.
        /// </summary>
        public static string Prompt_NameInvalid_Message {
            get {
                return ResourceManager.GetString("Prompt_NameInvalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Note.
        /// </summary>
        public static string Prompt_NameNote_Title {
            get {
                return ResourceManager.GetString("Prompt_NameNote_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string Prompt_NewFolder_Title {
            get {
                return ResourceManager.GetString("Prompt_NewFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A note of the same name already exists in the folder; please input a different name.
        /// </summary>
        public static string Prompt_NoteNameConflict_Message {
            get {
                return ResourceManager.GetString("Prompt_NoteNameConflict_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Name Conflict.
        /// </summary>
        public static string Prompt_NoteNameConflict_Title {
            get {
                return ResourceManager.GetString("Prompt_NoteNameConflict_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder of the same name already exists in QuickAccess, please input a different name.
        /// </summary>
        public static string Prompt_QuickAccessFolderNameConflict_Message {
            get {
                return ResourceManager.GetString("Prompt_QuickAccessFolderNameConflict_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A note of the same name already exists in QuickAccess, please input a different name.
        /// </summary>
        public static string Prompt_QuickAccessNoteNameConflict_Message {
            get {
                return ResourceManager.GetString("Prompt_QuickAccessNoteNameConflict_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        public static string Prompt_RenameFolder_Title {
            get {
                return ResourceManager.GetString("Prompt_RenameFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Note.
        /// </summary>
        public static string Prompt_RenameNote_Title {
            get {
                return ResourceManager.GetString("Prompt_RenameNote_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnly.
        /// </summary>
        public static string ReadonlyMarkerText {
            get {
                return ResourceManager.GetString("ReadonlyMarkerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Folder....
        /// </summary>
        public static string SearchBar_SearchFolder_Placeholder {
            get {
                return ResourceManager.GetString("SearchBar_SearchFolder_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color.
        /// </summary>
        public static string Settings_AccentColorSelector_Title {
            get {
                return ResourceManager.GetString("Settings_AccentColorSelector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        public static string Settings_CreateLocalBackup_Button {
            get {
                return ResourceManager.GetString("Settings_CreateLocalBackup_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string Settings_DarkThemeSwitch_Title {
            get {
                return ResourceManager.GetString("Settings_DarkThemeSwitch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Backup.
        /// </summary>
        public static string Settings_LocalBackup_Title {
            get {
                return ResourceManager.GetString("Settings_LocalBackup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        public static string Settings_RestoreLocalBackup_Button {
            get {
                return ResourceManager.GetString("Settings_RestoreLocalBackup_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Check Enabled.
        /// </summary>
        public static string Settings_SpellCheckEnabled_Title {
            get {
                return ResourceManager.GetString("Settings_SpellCheckEnabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name....
        /// </summary>
        public static string StyleSheetEntryPage_NamePlaceholder {
            get {
                return ResourceManager.GetString("StyleSheetEntryPage_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter CSS Text....
        /// </summary>
        public static string StyleSheetEntryPage_TextPlaceholder {
            get {
                return ResourceManager.GetString("StyleSheetEntryPage_TextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string Toolbar_AddFolder {
            get {
                return ResourceManager.GetString("Toolbar_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By.
        /// </summary>
        public static string Toolbar_OrderBy {
            get {
                return ResourceManager.GetString("Toolbar_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Folder.
        /// </summary>
        public static string Toolbar_SearchFolder {
            get {
                return ResourceManager.GetString("Toolbar_SearchFolder", resourceCulture);
            }
        }
    }
}
